before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.name={{.ProjectName}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
    - "pzmi/http-echo:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
    - "--platform=linux/amd64"
  - image_templates:
    - "pzmi/http-echo:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
    - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: pzmi/http-echo:{{ .Version }}
    image_templates:
    - pzmi/http-echo:{{ .Version }}-amd64
    - pzmi/http-echo:{{ .Version }}-arm64v8
  - name_template: pzmi/http-echo:latest
    image_templates:
    - pzmi/http-echo:{{ .Version }}-amd64
    - pzmi/http-echo:{{ .Version }}-arm64v8